worker: establish packit user via nss_wrapper
not sure what exactly has changed but git refuses to clone repos:

git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v git@gitlab.com:redhat/centos-stream/src/vulkan-loader.git /workdir/redhat/centos-stream/src/vulkan-loader
  stderr: 'Cloning into '/workdir/redhat/centos-stream/src/vulkan-loader'...
No user exists for uid 1000140000
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

This commit uses nss_wrapper to "create" a user during the worker startup so
that standard linux utilities get a real username via e.g. `getent`.

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>